// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use pooler URL — Neon free tier blocks direct TCP on port 5432 from outside Neon's network.
    url: process.env["DATABASE_URL"],
  },
});
